// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAssessment_DevelopersTodat.DAL.Context;

#nullable disable

namespace TestAssessment_DevelopersTodat.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20250317091644_MakePassengerCountNullable")]
    partial class MakePassengerCountNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestAssessment_DevelopersTodat.DAL.Models.CabData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DOLocationId")
                        .HasColumnType("int");

                    b.Property<double>("FareAmount")
                        .HasColumnType("float");

                    b.Property<int>("PULocationId")
                        .HasColumnType("int");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<string>("StoreAndFwdFlag")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<double>("TipAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("TpepDropoffDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TpepPickupDateTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("TripDistance")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PULocationId");

                    b.HasIndex("StoreAndFwdFlag");

                    b.HasIndex("TripDistance");

                    b.ToTable("CabData");
                });
#pragma warning restore 612, 618
        }
    }
}
